[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
# Ensure we run the server file.
cmd = "node server.js"
