#!/bin/bash
# Documentation Reorganization Script
# Generated by AI Audit (Gemini + ChatGPT)
# Issue: #1 - docs: Major Documentation Reorganization

set -e  # Exit on error

echo "🚀 Starting Documentation Reorganization..."
echo "Creating new folder structure..."

# Create new folder structure
mkdir -p docs/00-index
mkdir -p docs/architecture
mkdir -p docs/product
mkdir -p docs/sprints
mkdir -p docs/api
mkdir -p docs/testing
mkdir -p docs/status
mkdir -p docs/workflows

echo "✅ Folder structure created"
echo "📝 Moving files to new structure..."

# 00-index (Entry Point & Documentation Map)
if [ -f docs/.github/workflows/DOCUMENTATION-STRUCTURE.md ]; then
  git mv docs/.github/workflows/DOCUMENTATION-STRUCTURE.md docs/00-index/README.md
  echo "  ✅ Moved DOCUMENTATION-STRUCTURE.md -> 00-index/README.md"
fi

# Architecture (SRS, DB Schemas)
if [ -f docs/AI-Skincare-Intelligence-System-SRS-V5-2.md ]; then
  git mv docs/AI-Skincare-Intelligence-System-SRS-V5-2.md docs/architecture/srs-v5-2.md
  echo "  ✅ Moved SRS-V5-2 -> architecture/srs-v5-2.md"
fi

if [ -f docs/SRS-V5-1-DATABASE-UPDATE.md ]; then
  git mv docs/SRS-V5-1-DATABASE-UPDATE.md docs/architecture/database-update-v5-1.md
  echo "  ✅ Moved SRS-V5-1-DATABASE-UPDATE -> architecture/database-update-v5-1.md"
fi

if [ -f docs/DATABASE-TRANSITION-STRATEGY.md ]; then
  git mv docs/DATABASE-TRANSITION-STRATEGY.md docs/architecture/database-transition-strategy.md
  echo "  ✅ Moved DATABASE-TRANSITION-STRATEGY -> architecture/database-transition-strategy.md"
fi

# Product (Backlog, Tracker, Roadmap)
if [ -f docs/PRODUCT-BACKLOG.md ]; then
  git mv docs/PRODUCT-BACKLOG.md docs/product/backlog.md
  echo "  ✅ Moved PRODUCT-BACKLOG -> product/backlog.md"
fi

if [ -f docs/PROGRESS-TRACKER.md ]; then
  git mv docs/PROGRESS-TRACKER.md docs/product/progress-tracker.md
  echo "  ✅ Moved PROGRESS-TRACKER -> product/progress-tracker.md"
fi

# Sprints (Immutable sprint snapshots)
if [ -f docs/sprint1/SPRINT-1-REVIEW.md ]; then
  git mv docs/sprint1/SPRINT-1-REVIEW.md docs/sprints/sprint-1-review.md
  echo "  ✅ Moved SPRINT-1-REVIEW -> sprints/sprint-1-review.md"
fi

if [ -f docs/sprint1/SPRINT-1-IMPLEMENTATION-COMPLETE.md ]; then
  git mv docs/sprint1/SPRINT-1-IMPLEMENTATION-COMPLETE.md docs/sprints/sprint-1-implementation.md
  echo "  ✅ Moved SPRINT-1-IMPLEMENTATION-COMPLETE -> sprints/sprint-1-implementation.md"
fi

if [ -f docs/SPRINT-2-PHASE-3-COMPLETE.md ]; then
  git mv docs/SPRINT-2-PHASE-3-COMPLETE.md docs/sprints/sprint-2-phase-3-complete.md
  echo "  ✅ Moved SPRINT-2-PHASE-3-COMPLETE -> sprints/sprint-2-phase-3-complete.md"
fi

# API Documentation
if [ -f docs/API_TESTING_COMPLETE_REPORT.md ]; then
  git mv docs/API_TESTING_COMPLETE_REPORT.md docs/api/testing-complete-report.md
  echo "  ✅ Moved API_TESTING_COMPLETE_REPORT -> api/testing-complete-report.md"
fi

if [ -f docs/ADR-ML-003-External-Model-Storage-Service.md ]; then
  git mv docs/ADR-ML-003-External-Model-Storage-Service.md docs/api/adr-ml-003-external-storage.md
  echo "  ✅ Moved ADR-ML-003 -> api/adr-ml-003-external-storage.md"
fi

# Testing
if [ -f docs/BACKEND_TESTING_SUMMARY.md ]; then
  git mv docs/BACKEND_TESTING_SUMMARY.md docs/testing/backend-summary.md
  echo "  ✅ Moved BACKEND_TESTING_SUMMARY -> testing/backend-summary.md"
fi

if [ -f docs/TESTING-PHASE-AGILE-INTEGRATION.md ]; then
  git mv docs/TESTING-PHASE-AGILE-INTEGRATION.md docs/testing/phase-agile-integration.md
  echo "  ✅ Moved TESTING-PHASE-AGILE-INTEGRATION -> testing/phase-agile-integration.md"
fi

# Status (Living Docs - Current State)
if [ -f docs/BASELINE-HEALTHCHECK.md ]; then
  git mv docs/BASELINE-HEALTHCHECK.md docs/status/baseline-healthcheck.md
  echo "  ✅ Moved BASELINE-HEALTHCHECK -> status/baseline-healthcheck.md"
fi

if [ -f docs/CURRENT-STATE.md ]; then
  git mv docs/CURRENT-STATE.md docs/status/current-state.md
  echo "  ✅ Moved CURRENT-STATE -> status/current-state.md"
fi

if [ -f docs/ACTION-PLAN-TODAY.md ]; then
  git mv docs/ACTION-PLAN-TODAY.md docs/status/action-plan-today.md
  echo "  ✅ Moved ACTION-PLAN-TODAY -> status/action-plan-today.md"
fi

# Workflows (CI/CD, Agile Process)
if [ -f docs/AI_AGILE_WORKFLOW.md ]; then
  git mv docs/AI_AGILE_WORKFLOW.md docs/workflows/agile-workflow.md
  echo "  ✅ Moved AI_AGILE_WORKFLOW -> workflows/agile-workflow.md"
fi

if [ -f docs/CI-CD-DASHBOARD-APPROACH.md ]; then
  git mv docs/CI-CD-DASHBOARD-APPROACH.md docs/workflows/ci-cd-dashboard.md
  echo "  ✅ Moved CI-CD-DASHBOARD-APPROACH -> workflows/ci-cd-dashboard.md"
fi

echo "♻️ Removing duplicate files..."

# Remove duplicates (keep only the best version)
if [ -f docs/API-TESTING-REPORT.md ]; then
  rm docs/API-TESTING-REPORT.md
  echo "  ❌ Deleted API-TESTING-REPORT.md (duplicate)"
fi

if [ -f docs/AGILE-SPRINT-1.2-IMPLEMENTATION.md ]; then
  rm docs/AGILE-SPRINT-1.2-IMPLEMENTATION.md
  echo "  ❌ Deleted AGILE-SPRINT-1.2-IMPLEMENTATION.md (duplicate)"
fi

if [ -f docs/BACKEND_IMPROVEMENTS.md ]; then
  rm docs/BACKEND_IMPROVEMENTS.md
  echo "  ❌ Deleted BACKEND_IMPROVEMENTS.md (merged)"
fi

if [ -f docs/AUDIT-REPORT.md ]; then
  rm docs/AUDIT-REPORT.md
  echo "  ❌ Deleted AUDIT-REPORT.md (one-time audit)"
fi

echo ""
echo "✅ Reorganization Complete!"
echo ""
echo "📊 Summary:"
echo "  - Created 8 organizational folders"
echo "  - Moved critical documentation to proper locations"
echo "  - Removed duplicate/obsolete files"
echo "  - Applied kebab-case naming convention"
echo ""
echo "📝 Next Steps:"
echo "  1. Review changes: git status"
echo "  2. Commit changes: git commit -m 'docs: Major reorganization - Eliminate 80+ file bloat'"
echo "  3. Push to GitHub: git push origin docs-reorganization-v1"
echo "  4. Create Pull Request and link to Issue #1"
echo ""
echo "🎉 Documentation is now production-ready!"
