"""baseline

Revision ID: 6ee7976e52ce
Revises: 
Create Date: 2026-03-26 16:41:59.928994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ee7976e52ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('read_time_min', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogs_id'), 'blogs', ['id'], unique=False)
    op.create_index(op.f('ix_blogs_slug'), 'blogs', ['slug'], unique=True)
    op.create_table('ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_inci', sa.String(length=255), nullable=False),
    sa.Column('common_names', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('function', sa.Text(), nullable=True),
    sa.Column('safety_category', sa.String(length=50), nullable=True),
    sa.Column('safety_rating', sa.Integer(), nullable=True),
    sa.Column('comedogenic_rating', sa.Integer(), nullable=True),
    sa.Column('microbiome_impact', sa.String(length=50), nullable=True),
    sa.Column('is_antimicrobial', sa.Integer(), nullable=False),
    sa.Column('fda_approved', sa.Integer(), nullable=False),
    sa.Column('eu_approved', sa.Integer(), nullable=False),
    sa.Column('data_sources', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_name_inci'), 'ingredients', ['name_inci'], unique=True)
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_id'), 'news_items', ['id'], unique=False)
    op.create_table('policy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_type', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_url', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index(op.f('ix_policy_versions_id'), 'policy_versions', ['id'], unique=False)
    op.create_index(op.f('ix_policy_versions_policy_type'), 'policy_versions', ['policy_type'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('upc', sa.String(length=50), nullable=True),
    sa.Column('size_ml', sa.Float(), nullable=True),
    sa.Column('primary_concerns', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('skin_types', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('suitable_for', postgresql.ARRAY(String()), nullable=True),
    sa.Column('targets', postgresql.ARRAY(String()), nullable=True),
    sa.Column('is_fragrance_free', sa.Integer(), nullable=False),
    sa.Column('is_vegan', sa.Integer(), nullable=False),
    sa.Column('is_cruelty_free', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('product_image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_upc'), 'products', ['upc'], unique=False)
    op.create_table('skin_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skin_conditions_slug'), 'skin_conditions', ['slug'], unique=True)
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('chain', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('email_verification_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ip_address', sa.String(length=45), nullable=True),
    sa.Column('last_geolocation', sa.JSON(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email_verification_token'), 'users', ['email_verification_token'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.create_table('daily_skin_guidance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('guidance_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('uv_alert', sa.Text(), nullable=True),
    sa.Column('hydration_tip', sa.Text(), nullable=True),
    sa.Column('sunscreen_tip', sa.Text(), nullable=True),
    sa.Column('routine_tip', sa.Text(), nullable=True),
    sa.Column('reasoning', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_skin_guidance_guidance_date'), 'daily_skin_guidance', ['guidance_date'], unique=False)
    op.create_index(op.f('ix_daily_skin_guidance_user_id'), 'daily_skin_guidance', ['user_id'], unique=False)
    op.create_table('environment_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uv_index', sa.Float(), nullable=True),
    sa.Column('humidity_percent', sa.Float(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('air_quality_index', sa.Integer(), nullable=True),
    sa.Column('pollution_level', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('time_of_day', sa.String(length=20), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_recorded', 'environment_snapshots', ['user_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_environment_snapshots_recorded_at'), 'environment_snapshots', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_environment_snapshots_user_id'), 'environment_snapshots', ['user_id'], unique=False)
    op.create_table('geo_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_locations_user_id'), 'geo_locations', ['user_id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('routine_reminders', sa.Boolean(), nullable=True),
    sa.Column('progress_updates', sa.Boolean(), nullable=True),
    sa.Column('product_recommendations', sa.Boolean(), nullable=True),
    sa.Column('skin_change_alerts', sa.Boolean(), nullable=True),
    sa.Column('system_notifications', sa.Boolean(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=True),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_settings_id'), 'notification_settings', ['id'], unique=False)
    op.create_index(op.f('ix_notification_settings_user_id'), 'notification_settings', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'read'], unique=False)
    op.create_table('product_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('concentration_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_ingredients_ingredient_id'), 'product_ingredients', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_product_ingredients_product_id'), 'product_ingredients', ['product_id'], unique=False)
    op.create_table('product_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('offer_url', sa.String(length=500), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_offers_product_id'), 'product_offers', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_offers_store_id'), 'product_offers', ['store_id'], unique=False)
    op.create_table('product_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('skin_type', sa.String(length=50), nullable=True),
    sa.Column('would_recommend', sa.Integer(), nullable=True),
    sa.Column('verified_purchase', sa.Integer(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_reviews_created_at', 'product_reviews', ['created_at'], unique=False)
    op.create_index('ix_product_reviews_product_created', 'product_reviews', ['product_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_product_reviews_product_id'), 'product_reviews', ['product_id'], unique=False)
    op.create_index('ix_product_reviews_product_user', 'product_reviews', ['product_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_product_reviews_user_id'), 'product_reviews', ['user_id'], unique=False)
    op.create_table('product_scan_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.Column('image_content_type', sa.String(length=100), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('scan_metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_scan_sessions_status'), 'product_scan_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_product_scan_sessions_user_id'), 'product_scan_sessions', ['user_id'], unique=False)
    op.create_table('product_store_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('purchase_url', sa.String(length=500), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_store_availability_product_id'), 'product_store_availability', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_store_availability_store_id'), 'product_store_availability', ['store_id'], unique=False)
    op.create_table('routine_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('routine_type', sa.String(length=20), nullable=False),
    sa.Column('routine_name', sa.String(length=100), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('mood', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_routine_type', 'routine_instances', ['routine_type'], unique=False)
    op.create_index('idx_user_executed', 'routine_instances', ['user_id', 'executed_at'], unique=False)
    op.create_index(op.f('ix_routine_instances_executed_at'), 'routine_instances', ['executed_at'], unique=False)
    op.create_index(op.f('ix_routine_instances_user_id'), 'routine_instances', ['user_id'], unique=False)
    op.create_table('saved_routines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('routine_type', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=True),
    sa.Column('reminder_time', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='scanstatus'), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.Column('image_content_type', sa.String(length=100), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('scan_metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_sessions_created_at'), 'scan_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_sessions_status'), 'scan_sessions', ['status'], unique=False)
    op.create_index('ix_scan_sessions_user_created', 'scan_sessions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_scan_sessions_user_id'), 'scan_sessions', ['user_id'], unique=False)
    op.create_table('shelf_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('external_product_id', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_brand', sa.String(length=255), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('product_image', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('routine_type', sa.String(length=20), nullable=True),
    sa.Column('routine_order', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('would_repurchase', sa.Boolean(), nullable=True),
    sa.Column('times_repurchased', sa.Integer(), nullable=True),
    sa.Column('ingredients_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shelf_products_category', 'shelf_products', ['product_category'], unique=False)
    op.create_index('ix_shelf_products_created_at', 'shelf_products', ['created_at'], unique=False)
    op.create_index(op.f('ix_shelf_products_external_product_id'), 'shelf_products', ['external_product_id'], unique=False)
    op.create_index(op.f('ix_shelf_products_id'), 'shelf_products', ['id'], unique=False)
    op.create_index('ix_shelf_products_routine_type', 'shelf_products', ['routine_type'], unique=False)
    op.create_index('ix_shelf_products_status', 'shelf_products', ['status'], unique=False)
    op.create_index(op.f('ix_shelf_products_user_id'), 'shelf_products', ['user_id'], unique=False)
    op.create_index('ix_shelf_products_user_status', 'shelf_products', ['user_id', 'status'], unique=False)
    op.create_table('skin_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('metric_unit', sa.String(length=50), nullable=True),
    sa.Column('milestones', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skin_goals_id'), 'skin_goals', ['id'], unique=False)
    op.create_index(op.f('ix_skin_goals_user_id'), 'skin_goals', ['user_id'], unique=False)
    op.create_table('user_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('geolocation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_access_logs_id'), 'user_access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_user_access_logs_user_id'), 'user_access_logs', ['user_id'], unique=False)
    op.create_table('user_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('terms_accepted', sa.Boolean(), nullable=True),
    sa.Column('privacy_accepted', sa.Boolean(), nullable=True),
    sa.Column('terms_version', sa.String(), nullable=False),
    sa.Column('privacy_version', sa.String(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_consents_id'), 'user_consents', ['id'], unique=False)
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.create_table('user_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_events_event_type'), 'user_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_events_user_id'), 'user_events', ['user_id'], unique=False)
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('external_product_id', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_brand', sa.String(length=255), nullable=True),
    sa.Column('product_price', sa.Float(), nullable=True),
    sa.Column('product_image', sa.String(length=500), nullable=True),
    sa.Column('product_rating', sa.Float(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favorites_external_product_id'), 'user_favorites', ['external_product_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_id'), 'user_favorites', ['id'], unique=False)
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    op.create_table('user_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notifications_notification_type'), 'user_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('skin_type', sa.Text(), nullable=True),
    sa.Column('skin_tone', sa.String(length=50), nullable=True),
    sa.Column('skin_texture', sa.String(length=50), nullable=True),
    sa.Column('pore_size', sa.String(length=20), nullable=True),
    sa.Column('moisture_level', sa.String(length=20), nullable=True),
    sa.Column('oil_production', sa.String(length=20), nullable=True),
    sa.Column('sensitivity_level', sa.String(length=20), nullable=True),
    sa.Column('primary_concern', sa.String(length=100), nullable=True),
    sa.Column('secondary_concerns', sa.JSON(), nullable=True),
    sa.Column('sun_exposure', sa.String(length=20), nullable=True),
    sa.Column('outdoor_activity_level', sa.String(length=20), nullable=True),
    sa.Column('water_intake', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('diet_type', sa.String(length=50), nullable=True),
    sa.Column('stress_level', sa.String(length=20), nullable=True),
    sa.Column('exercise_frequency', sa.String(length=50), nullable=True),
    sa.Column('smoking_status', sa.String(length=20), nullable=True),
    sa.Column('alcohol_consumption', sa.String(length=20), nullable=True),
    sa.Column('climate', sa.String(length=50), nullable=True),
    sa.Column('known_allergies', sa.JSON(), nullable=True),
    sa.Column('current_medications', sa.JSON(), nullable=True),
    sa.Column('skin_conditions', sa.JSON(), nullable=True),
    sa.Column('previous_treatments', sa.Text(), nullable=True),
    sa.Column('preferred_ingredients', sa.JSON(), nullable=True),
    sa.Column('ingredients_to_avoid', sa.JSON(), nullable=True),
    sa.Column('product_texture_preference', sa.String(length=50), nullable=True),
    sa.Column('fragrance_preference', sa.String(length=30), nullable=True),
    sa.Column('budget_range', sa.String(length=30), nullable=True),
    sa.Column('brand_preferences', sa.JSON(), nullable=True),
    sa.Column('routine_frequency', sa.String(length=50), nullable=True),
    sa.Column('current_routine_products', sa.JSON(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('sms_notifications', sa.Boolean(), nullable=True),
    sa.Column('marketing_emails', sa.Boolean(), nullable=True),
    sa.Column('profile_visibility', sa.String(length=20), nullable=True),
    sa.Column('share_progress', sa.Boolean(), nullable=True),
    sa.Column('allow_data_analysis', sa.Boolean(), nullable=True),
    sa.Column('profile_complete', sa.Boolean(), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('last_profile_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('user_progress_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('hydration', sa.Float(), nullable=True),
    sa.Column('acne', sa.Float(), nullable=True),
    sa.Column('redness', sa.Float(), nullable=True),
    sa.Column('wrinkles', sa.Float(), nullable=True),
    sa.Column('pigmentation', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_snapshots_snapshot_date'), 'user_progress_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_user_progress_snapshots_user_id'), 'user_progress_snapshots', ['user_id'], unique=False)
    op.create_table('environmental_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('uv_index', sa.Float(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('humidity_percent', sa.Float(), nullable=True),
    sa.Column('air_quality_index', sa.Integer(), nullable=True),
    sa.Column('pollen_index', sa.Integer(), nullable=True),
    sa.Column('weather_conditions', sa.String(length=100), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['geo_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmental_readings_location_id'), 'environmental_readings', ['location_id'], unique=False)
    op.create_table('geo_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('uv_index', sa.Float(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['geo_locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_alerts_location_id'), 'geo_alerts', ['location_id'], unique=False)
    op.create_index(op.f('ix_geo_alerts_user_id'), 'geo_alerts', ['user_id'], unique=False)
    op.create_table('notification_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['user_notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_events_notification_id'), 'notification_events', ['notification_id'], unique=False)
    op.create_table('product_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_session_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['scan_session_id'], ['scan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_recommendations_product_id'), 'product_recommendations', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_recommendations_scan_session_id'), 'product_recommendations', ['scan_session_id'], unique=False)
    op.create_table('product_scan_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_session_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('matched_name', sa.String(length=300), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['scan_session_id'], ['product_scan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_scan_items_product_id'), 'product_scan_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_scan_items_scan_session_id'), 'product_scan_items', ['scan_session_id'], unique=False)
    op.create_table('progress_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.UUID(), nullable=True),
    sa.Column('photo_type', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('photo_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['saved_routines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routine_checkins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('routine_instance_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['routine_instance_id'], ['routine_instances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_checkins_routine_instance_id'), 'routine_checkins', ['routine_instance_id'], unique=False)
    op.create_index(op.f('ix_routine_checkins_user_id'), 'routine_checkins', ['user_id'], unique=False)
    op.create_table('routine_product_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('routine_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('amount_used', sa.String(length=50), nullable=True),
    sa.Column('application_area', sa.String(length=100), nullable=True),
    sa.Column('effectiveness_rating', sa.Integer(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routine_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_routine_step', 'routine_product_usage', ['routine_id', 'step_order'], unique=False)
    op.create_index(op.f('ix_routine_product_usage_product_id'), 'routine_product_usage', ['product_id'], unique=False)
    op.create_index(op.f('ix_routine_product_usage_routine_id'), 'routine_product_usage', ['routine_id'], unique=False)
    op.create_table('routine_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scan_session_id', sa.UUID(), nullable=True),
    sa.Column('product_scan_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_scan_id'], ['product_scan_sessions.id'], ),
    sa.ForeignKeyConstraint(['scan_session_id'], ['scan_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_recommendations_product_scan_id'), 'routine_recommendations', ['product_scan_id'], unique=False)
    op.create_index(op.f('ix_routine_recommendations_scan_session_id'), 'routine_recommendations', ['scan_session_id'], unique=False)
    op.create_index(op.f('ix_routine_recommendations_user_id'), 'routine_recommendations', ['user_id'], unique=False)
    op.create_table('scan_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_session_id', sa.UUID(), nullable=False),
    sa.Column('condition_id', sa.UUID(), nullable=False),
    sa.Column('severity_label', sa.String(length=20), nullable=True),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('affected_regions', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['skin_conditions.id'], ),
    sa.ForeignKeyConstraint(['scan_session_id'], ['scan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_conditions_condition_id'), 'scan_conditions', ['condition_id'], unique=False)
    op.create_index(op.f('ix_scan_conditions_scan_session_id'), 'scan_conditions', ['scan_session_id'], unique=False)
    op.create_table('scan_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_session_id', sa.UUID(), nullable=False),
    sa.Column('raw_result', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('normalized_result', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_session_id'], ['scan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_outputs_scan_session_id'), 'scan_outputs', ['scan_session_id'], unique=False)
    op.create_table('scan_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_session_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_session_id'], ['scan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_recommendations_scan_session_id'), 'scan_recommendations', ['scan_session_id'], unique=False)
    op.create_table('skin_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_session_id', sa.UUID(), nullable=False),
    sa.Column('skin_type', sa.Enum('NORMAL', 'DRY', 'OILY', 'COMBINATION', 'SENSITIVE', name='skintype'), nullable=False),
    sa.Column('fitzpatrick_scale', sa.Integer(), nullable=False),
    sa.Column('concerns', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('landmarks', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('confidence_scores', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('analysis_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_session_id'], ['scan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skin_analyses_created_at'), 'skin_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_skin_analyses_scan_session_id'), 'skin_analyses', ['scan_session_id'], unique=True)
    op.create_table('skin_state_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scan_session_id', sa.UUID(), nullable=False),
    sa.Column('overall_health_score', sa.Float(), nullable=False),
    sa.Column('hydration_level', sa.Float(), nullable=False),
    sa.Column('oil_level', sa.Float(), nullable=False),
    sa.Column('sensitivity_score', sa.Float(), nullable=False),
    sa.Column('acne_severity', sa.Float(), nullable=True),
    sa.Column('wrinkle_severity', sa.Float(), nullable=True),
    sa.Column('pigmentation_severity', sa.Float(), nullable=True),
    sa.Column('redness_severity', sa.Float(), nullable=True),
    sa.Column('environment_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('recent_routine_id', sa.UUID(), nullable=True),
    sa.Column('ml_model_version', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_snapshot_id'], ['environment_snapshots.id'], ),
    sa.ForeignKeyConstraint(['recent_routine_id'], ['routine_instances.id'], ),
    sa.ForeignKeyConstraint(['scan_session_id'], ['scan_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_snapshot_date', 'skin_state_snapshots', ['user_id', 'snapshot_date'], unique=False)
    op.create_index(op.f('ix_skin_state_snapshots_scan_session_id'), 'skin_state_snapshots', ['scan_session_id'], unique=False)
    op.create_index(op.f('ix_skin_state_snapshots_snapshot_date'), 'skin_state_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_skin_state_snapshots_user_id'), 'skin_state_snapshots', ['user_id'], unique=False)
    op.create_table('confidence_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('concern_confidences', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('uncertainty_factors', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('image_quality_score', sa.Float(), nullable=True),
    sa.Column('lighting_quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['skin_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confidence_metrics_analysis_id'), 'confidence_metrics', ['analysis_id'], unique=True)
    op.create_table('fairness_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('fitzpatrick_scale', sa.Integer(), nullable=False),
    sa.Column('accuracy_by_tone', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('bias_indicators', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['skin_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fairness_metrics_analysis_id'), 'fairness_metrics', ['analysis_id'], unique=True)
    op.create_index(op.f('ix_fairness_metrics_fitzpatrick_scale'), 'fairness_metrics', ['fitzpatrick_scale'], unique=False)
    op.create_table('skin_region_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('region_name', sa.String(length=50), nullable=False),
    sa.Column('region_type', sa.String(length=30), nullable=False),
    sa.Column('texture_score', sa.Float(), nullable=False),
    sa.Column('acne_severity', sa.Float(), nullable=False),
    sa.Column('redness_level', sa.Float(), nullable=False),
    sa.Column('pigmentation_level', sa.Float(), nullable=False),
    sa.Column('oil_level', sa.Float(), nullable=False),
    sa.Column('hydration_level', sa.Float(), nullable=False),
    sa.Column('sensitivity_score', sa.Float(), nullable=False),
    sa.Column('heatmap_url', sa.String(length=500), nullable=True),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('concerns', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['skin_state_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshot_region', 'skin_region_states', ['snapshot_id', 'region_name'], unique=False)
    op.create_index(op.f('ix_skin_region_states_snapshot_id'), 'skin_region_states', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skin_region_states_snapshot_id'), table_name='skin_region_states')
    op.drop_index('idx_snapshot_region', table_name='skin_region_states')
    op.drop_table('skin_region_states')
    op.drop_index(op.f('ix_fairness_metrics_fitzpatrick_scale'), table_name='fairness_metrics')
    op.drop_index(op.f('ix_fairness_metrics_analysis_id'), table_name='fairness_metrics')
    op.drop_table('fairness_metrics')
    op.drop_index(op.f('ix_confidence_metrics_analysis_id'), table_name='confidence_metrics')
    op.drop_table('confidence_metrics')
    op.drop_index(op.f('ix_skin_state_snapshots_user_id'), table_name='skin_state_snapshots')
    op.drop_index(op.f('ix_skin_state_snapshots_snapshot_date'), table_name='skin_state_snapshots')
    op.drop_index(op.f('ix_skin_state_snapshots_scan_session_id'), table_name='skin_state_snapshots')
    op.drop_index('idx_user_snapshot_date', table_name='skin_state_snapshots')
    op.drop_table('skin_state_snapshots')
    op.drop_index(op.f('ix_skin_analyses_scan_session_id'), table_name='skin_analyses')
    op.drop_index(op.f('ix_skin_analyses_created_at'), table_name='skin_analyses')
    op.drop_table('skin_analyses')
    op.drop_index(op.f('ix_scan_recommendations_scan_session_id'), table_name='scan_recommendations')
    op.drop_table('scan_recommendations')
    op.drop_index(op.f('ix_scan_outputs_scan_session_id'), table_name='scan_outputs')
    op.drop_table('scan_outputs')
    op.drop_index(op.f('ix_scan_conditions_scan_session_id'), table_name='scan_conditions')
    op.drop_index(op.f('ix_scan_conditions_condition_id'), table_name='scan_conditions')
    op.drop_table('scan_conditions')
    op.drop_index(op.f('ix_routine_recommendations_user_id'), table_name='routine_recommendations')
    op.drop_index(op.f('ix_routine_recommendations_scan_session_id'), table_name='routine_recommendations')
    op.drop_index(op.f('ix_routine_recommendations_product_scan_id'), table_name='routine_recommendations')
    op.drop_table('routine_recommendations')
    op.drop_index(op.f('ix_routine_product_usage_routine_id'), table_name='routine_product_usage')
    op.drop_index(op.f('ix_routine_product_usage_product_id'), table_name='routine_product_usage')
    op.drop_index('idx_routine_step', table_name='routine_product_usage')
    op.drop_table('routine_product_usage')
    op.drop_index(op.f('ix_routine_checkins_user_id'), table_name='routine_checkins')
    op.drop_index(op.f('ix_routine_checkins_routine_instance_id'), table_name='routine_checkins')
    op.drop_table('routine_checkins')
    op.drop_table('progress_photos')
    op.drop_index(op.f('ix_product_scan_items_scan_session_id'), table_name='product_scan_items')
    op.drop_index(op.f('ix_product_scan_items_product_id'), table_name='product_scan_items')
    op.drop_table('product_scan_items')
    op.drop_index(op.f('ix_product_recommendations_scan_session_id'), table_name='product_recommendations')
    op.drop_index(op.f('ix_product_recommendations_product_id'), table_name='product_recommendations')
    op.drop_table('product_recommendations')
    op.drop_index(op.f('ix_notification_events_notification_id'), table_name='notification_events')
    op.drop_table('notification_events')
    op.drop_index(op.f('ix_geo_alerts_user_id'), table_name='geo_alerts')
    op.drop_index(op.f('ix_geo_alerts_location_id'), table_name='geo_alerts')
    op.drop_table('geo_alerts')
    op.drop_index(op.f('ix_environmental_readings_location_id'), table_name='environmental_readings')
    op.drop_table('environmental_readings')
    op.drop_index(op.f('ix_user_progress_snapshots_user_id'), table_name='user_progress_snapshots')
    op.drop_index(op.f('ix_user_progress_snapshots_snapshot_date'), table_name='user_progress_snapshots')
    op.drop_table('user_progress_snapshots')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_notification_type'), table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_external_product_id'), table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index(op.f('ix_user_events_user_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_event_type'), table_name='user_events')
    op.drop_table('user_events')
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_index(op.f('ix_user_consents_id'), table_name='user_consents')
    op.drop_table('user_consents')
    op.drop_index(op.f('ix_user_access_logs_user_id'), table_name='user_access_logs')
    op.drop_index(op.f('ix_user_access_logs_id'), table_name='user_access_logs')
    op.drop_table('user_access_logs')
    op.drop_index(op.f('ix_skin_goals_user_id'), table_name='skin_goals')
    op.drop_index(op.f('ix_skin_goals_id'), table_name='skin_goals')
    op.drop_table('skin_goals')
    op.drop_index('ix_shelf_products_user_status', table_name='shelf_products')
    op.drop_index(op.f('ix_shelf_products_user_id'), table_name='shelf_products')
    op.drop_index('ix_shelf_products_status', table_name='shelf_products')
    op.drop_index('ix_shelf_products_routine_type', table_name='shelf_products')
    op.drop_index(op.f('ix_shelf_products_id'), table_name='shelf_products')
    op.drop_index(op.f('ix_shelf_products_external_product_id'), table_name='shelf_products')
    op.drop_index('ix_shelf_products_created_at', table_name='shelf_products')
    op.drop_index('ix_shelf_products_category', table_name='shelf_products')
    op.drop_table('shelf_products')
    op.drop_index(op.f('ix_scan_sessions_user_id'), table_name='scan_sessions')
    op.drop_index('ix_scan_sessions_user_created', table_name='scan_sessions')
    op.drop_index(op.f('ix_scan_sessions_status'), table_name='scan_sessions')
    op.drop_index(op.f('ix_scan_sessions_created_at'), table_name='scan_sessions')
    op.drop_table('scan_sessions')
    op.drop_table('saved_routines')
    op.drop_index(op.f('ix_routine_instances_user_id'), table_name='routine_instances')
    op.drop_index(op.f('ix_routine_instances_executed_at'), table_name='routine_instances')
    op.drop_index('idx_user_executed', table_name='routine_instances')
    op.drop_index('idx_routine_type', table_name='routine_instances')
    op.drop_table('routine_instances')
    op.drop_index(op.f('ix_product_store_availability_store_id'), table_name='product_store_availability')
    op.drop_index(op.f('ix_product_store_availability_product_id'), table_name='product_store_availability')
    op.drop_table('product_store_availability')
    op.drop_index(op.f('ix_product_scan_sessions_user_id'), table_name='product_scan_sessions')
    op.drop_index(op.f('ix_product_scan_sessions_status'), table_name='product_scan_sessions')
    op.drop_table('product_scan_sessions')
    op.drop_index(op.f('ix_product_reviews_user_id'), table_name='product_reviews')
    op.drop_index('ix_product_reviews_product_user', table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_product_id'), table_name='product_reviews')
    op.drop_index('ix_product_reviews_product_created', table_name='product_reviews')
    op.drop_index('ix_product_reviews_created_at', table_name='product_reviews')
    op.drop_table('product_reviews')
    op.drop_index(op.f('ix_product_offers_store_id'), table_name='product_offers')
    op.drop_index(op.f('ix_product_offers_product_id'), table_name='product_offers')
    op.drop_table('product_offers')
    op.drop_index(op.f('ix_product_ingredients_product_id'), table_name='product_ingredients')
    op.drop_index(op.f('ix_product_ingredients_ingredient_id'), table_name='product_ingredients')
    op.drop_table('product_ingredients')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_settings_user_id'), table_name='notification_settings')
    op.drop_index(op.f('ix_notification_settings_id'), table_name='notification_settings')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_geo_locations_user_id'), table_name='geo_locations')
    op.drop_table('geo_locations')
    op.drop_index(op.f('ix_environment_snapshots_user_id'), table_name='environment_snapshots')
    op.drop_index(op.f('ix_environment_snapshots_recorded_at'), table_name='environment_snapshots')
    op.drop_index('idx_user_recorded', table_name='environment_snapshots')
    op.drop_table('environment_snapshots')
    op.drop_index(op.f('ix_daily_skin_guidance_user_id'), table_name='daily_skin_guidance')
    op.drop_index(op.f('ix_daily_skin_guidance_guidance_date'), table_name='daily_skin_guidance')
    op.drop_table('daily_skin_guidance')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stores')
    op.drop_index(op.f('ix_skin_conditions_slug'), table_name='skin_conditions')
    op.drop_table('skin_conditions')
    op.drop_index(op.f('ix_products_upc'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_policy_versions_policy_type'), table_name='policy_versions')
    op.drop_index(op.f('ix_policy_versions_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_news_items_id'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_ingredients_name_inci'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_blogs_slug'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_id'), table_name='blogs')
    op.drop_table('blogs')
    # ### end Alembic commands ###
